#!/bin/sh

set -eu

if [ $# -eq 0 ]; then
    sunbeam query -n '{
        title: "Store",
        commands: [
            {
                name: "browse",
                title: "Browse Extensions",
                mode: "view",
            },
            {
                name: "view-readme",
                title: "View Extension README",
                mode: "view",
                params: [
                    { name: "repo", type: "string", required: true }
                ]
            }
        ]
    }'
    exit 0
fi

if [ "$1" = "browse" ]; then
    sunbeam fetch 'https://api.github.com/search/repositories?q=topic:sunbeam-extension' | sunbeam query '.items | map({
        title: .name,
        subtitle: .owner.login,
        accessories: [(.description // "")],
        actions: [
            {
                title: "View README",
                onAction: {
                    type: "run",
                    command: "view-readme",
                    params: { repo: .full_name }
                }
            },
            {
                title: "Open in browser",
                key: "o",
                onAction: {
                    type: "open",
                    target: .html_url,
                    exit: true
                }
            },
            {
                title: "Copy URL",
                key: "c",
                onAction: {
                    type: "copy",
                    text: .html_url,
                    exit: true
                }
            }
        ]
    }) | {type: "list", items: .}'
elif [ "$1" = "view-readme" ]; then
    REPO=$(sunbeam query -r '.params.repo')
    # shellcheck disable=SC2016
    sunbeam fetch "https://api.github.com/repos/$REPO/readme" | sunbeam query --arg repo="$REPO" '{
        type: "detail",
        markdown: (.content | @base64d),
        actions: [
            {
                title: "Copy Install Command",
                onAction: {
                    type: "copy",
                    text: "sunbeam extension install https://github.com/\($repo)",
                    exit: true
                }
            },
            {
                title: "Open in browser",
                onAction: {
                    type: "open",
                    target: .html_url,
                    exit: true
                }
            }
        ]
    }'
fi
